# Generated by Django 3.0.6 on 2020-05-31 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('lat', models.CharField(max_length=30)),
                ('long', models.CharField(max_length=30)),
                ('score', models.CharField(max_length=30)),
            ],
        ),
    ]
