# Generated by Django 3.0.6 on 2020-05-31 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
    ]
